services:
  pihole:
    container_name: ${PIHOLE_CONTAINER_NAME:-pihole}
    image: ${PIHOLE_IMAGE:-pihole/pihole:latest}
    hostname: ${PIHOLE_HOSTNAME:-home.server}
    domainname: ${PIHOLE_DOMAINNAME:-pi-hole}
    ports:
      - ${PIHOLE_HTTPS_PORT:-443}:443/tcp
      - ${PIHOLE_DNS_PORT:-53}:53/tcp
      - ${PIHOLE_DNS_PORT:-53}:53/udp
      - ${PIHOLE_HTTP_PORT:-80}:80/tcp
    environment:
      - TZ=${TZ:-Europe/Kyiv}
      - DNSMASQ_USER=root
      - FTLCONF_webserver_api_password=${PIHOLE_WEBPASSWORD}
      - FTLCONF_dns_upstreams=knot#53
      - FTLCONF_dns_dnssec=true
      - FTLCONF_dns_listeningMode=all
    cap_add:
      - NET_ADMIN
    volumes:
      - ${PIHOLE_ETC:-/home/trip/pihole/etc-pihole}:/etc/pihole:rw
      - ${PIHOLE_DNSMASQ:-/home/trip/pihole/etc-dnsmasq.d}:/etc/dnsmasq.d:rw
    depends_on:
      knot:
        condition: service_healthy
    restart: unless-stopped

  knot:
    container_name: ${KNOT_CONTAINER_NAME:-knot}
    image: ${KNOT_IMAGE:-cznic/knot-resolver:v6.4.2}
    expose:
      - 53/tcp
      - 53/udp
    volumes:
      - ${KNOT_CONFIG_FILE:-/home/trip/knot/config.yaml}:/etc/knot-resolver/config.yaml:ro
      - ${KNOT_CACHE:-/home/trip/knot/cache}:/var/cache/knot-resolver
    healthcheck:
      test: ["CMD", "kdig", "+short", "+timeout=5", "+retry=1", "@127.0.0.1", "example.com"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale:latest
    container_name: ${TAILSCALE_CONTAINER_NAME:-tailscale}
    hostname: ${TS_HOSTNAME:-homeserver-vpn}
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${TAILSCALE_STATE:-/home/trip/tailscale/state}:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=true
      - TS_EXTRA_ARGS=${TS_EXTRA_ARGS:---advertise-exit-node --advertise-routes=192.168.1.0/24 --accept-dns=true}
    restart: unless-stopped
