services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: ${STIRLING_CONTAINER_NAME:-stirling-pdf}
    ports:
      - "${STIRLING_PORT:-3010}:8080"
    volumes:
      - ${STIRLING_TESSDATA:-/home/trip/stirling-pdf/tessdata}:/usr/share/tessdata
      - ${STIRLING_CONFIG:-/home/trip/stirling-pdf/configs}:/configs
    restart: unless-stopped